"""empty message

Revision ID: 65367f264ced
Revises: d355051ea30b
Create Date: 2020-05-26 01:40:37.925558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65367f264ced'
down_revision = 'd355051ea30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('email1', sa.String(length=120), nullable=True))
    op.drop_constraint('user_test_email_key', 'user_test', type_='unique')
    op.create_unique_constraint(None, 'user_test', ['email1'])
    op.drop_column('user_test', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_test', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_test', type_='unique')
    op.create_unique_constraint('user_test_email_key', 'user_test', ['email'])
    op.drop_column('user_test', 'email1')
    # ### end Alembic commands ###
