"""empty message

Revision ID: 9a5f6ed24083
Revises: 65367f264ced
Create Date: 2020-05-26 01:43:14.046885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a5f6ed24083'
down_revision = '65367f264ced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('email1', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email1'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('user_test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_test',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('email1', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_test_pkey'),
    sa.UniqueConstraint('email1', name='user_test_email1_key'),
    sa.UniqueConstraint('username', name='user_test_username_key')
    )
    op.drop_table('article_user')
    # ### end Alembic commands ###
